const tools = require('./tools.js')
const config = tools.getConfig()

module.exports = async function() {
  const domains = config.env.domains.map(d => `-d ${d}`).join(' ')
  const hostname = tools.safeHostname()
  tools.run('update.sh')
  tools.run('system.sh', hostname)
  tools.run('shell.sh')
  // tools.run('certbot.sh', config.env.email, domains)
  // tools.fetch(config.env.key, './.sverd/letsencrypt')
  // tools.fetch(config.env.cert, './.sverd/letsencrypt')
  console.log(`\nCopied SSL certificate files to './.sverd/letsencrypt'`)
  tools.run('nginx.sh')
  tools.run('mongodb.sh')
  tools.run('waveorb.sh', config.env.dir, config.env.exec)
  tools.run('firewall.sh')
  tools.put('./config/etc')
  tools.env('/etc/nginx/conf.d/proxy.conf', 'names', 'cert', 'key', 'dir', 'pass')
  tools.env('/etc/systemd/system/appserver@.service', 'dir', 'exec', 'description')
  tools.put('./config/usr')
  // tools.run('start.sh')
  // tools.run('reboot.sh')
  // console.log('\nPlease wait, rebooting...')
  // await new Promise(r => setTimeout(r, 5000))
  // tools.ping()
  console.log('Done!')
  console.log(`\nLog in to server: ssh root@${config.ip}`)
}
