const tools = require('./tools.js')

module.exports = async function() {
  tools.run('update.sh')
  tools.run('system.sh')
  tools.run('shell.sh')
  tools.run('certbot.sh')
  tools.run('nginx.sh')
  tools.run('mongodb.sh')
  tools.run('waveorb.sh')
  tools.run('firewall.sh')
  tools.scp('./config/etc')
  tools.scp('./config/usr')
  tools.env('/etc/nginx/conf.d/proxy.conf', 'names', 'cert', 'key')
  tools.env('/etc/systemd/system/appserver@.service', 'exec')
  tools.run('start.sh')
  tools.run('reboot.sh')
  console.log('\nPlease wait, rebooting...')
  tools.ping()
  console.log('Done!')
}
